<?php

/**
 * Implements hook_flush_caches().
 */
function at_tools_flush_caches() {

	$theme_list = list_themes(TRUE);
	$count = 0;
	//We need this hook to submit form settings button programmatically.
	foreach ($theme_list as $theme_name) {

		if ($theme_name->status == 1) {
			$form_state['build_info']['args'][0] = $theme_name->name;
			$form_state['values'] = array();
			module_load_include('inc', 'system', 'system.admin');
			drupal_form_submit('system_theme_settings', $form_state);
			drupal_set_message(t('Cached CSS files rebuilt for !themename', array('!themename' => $theme_name->name)), 'status');
			$count++;
		}
	}

	drupal_set_message(t('!amount themes have been rebuilt', array('!amount' => $count)), 'status');
}
